myExampleForm:
  extends:                  sfGuardUserForm
  name_format:              example[%s]
  fields:
    name:
      label:                And your name is?
      help:                 Be a nice guy, enter your real name.
      required:
        msg:                Please enter your name.
      sfValidatorString:
        min_length:         2
        min_length_error:   Your name must be at least two characters long.
        max_length:         255
        max_length_error:   Your name cannot be longer than 255 characters.
    email:
      required:
        msg:                Please enter your email address.
      sfValidatorString:    ~
      sfValidatorEmail:     ~
    birthday:
      type:                 date
      year_from:            -18 years
    some_time:
      type:                 time
    gender:
      type:                 radio
      choices:              { male: Male, female, Female }
      required:
        msg:                Please select your gender.
