<?php

/**
 * Generation logic for sfFormtastic YAML forms.
 * 
 * @package     sfFormtasticPlugin
 * @subpackage  generator
 * @author      Kris Wallsmith
 * @version     SVN: $Id$
 */
class sfFormtasticGeneratorManager extends sfFormtasticGeneratorBase
{
  protected
    $forms = array();
  
  /**
   * Constructor.
   * 
   * @param   array $config
   */
  public function __construct($config = array())
  {
    $this->initialize($config);
  }
  
  /**
   * Initialize the generator.
   * 
   * @param   array $config
   */
  public function initialize($config = array())
  {
    foreach ($config as $class => $params)
    {
      $this->forms[] = new sfFormtasticGeneratorForm($class, $params);
    }
  }
  
  /**
   * Generate the configured form classes.
   * 
   * @return  string
   */
  public function generate()
  {
    $data = array();
    
    $data[] = '<?php';
    $data[] = '';
    $data[] = '/*';
    $data[] = ' * auto-generated by '.__CLASS__;
    $data[] = ' * date: '.date('Y/m/d H:i:s');
    $data[] = ' */';
    $data[] = '';
    
    foreach ($this->forms as $form)
    {
      $data[] = $form->generate();
    }
    
    return join("\n", $data);
  }
}
